Day 23: Coprocessor Conflagration
=================================

https://adventofcode.com/2017/day/23

Part 1
------

This puzzle adds some instructions to the architecture described on link:https://adventofcode.com/2017/day/18[day 18]. Part 1 asks you to simulate a program containing a subset of these instructions and count the number of times the `mul` instruction is invoked.

I extended link:../day18/[my solution from day 18] to include support for the new instructions and log uses of `mul` to `stdout`. The answer to part 1 is obtained by wrapping the simulator from day 18 in a shell script that counts the number of times `mul` has been logged.

Part 2
------

The second part of the puzzle asks you what value would be left in the `h` register after the program runs to completion, with a minor change to register initialization: Register `a` now starts at `1` (instead of `0`).

The program seems to be running for a _very_ long time in this configuration, and the puzzle text suggests that some kind of code optimization might be neccesary to complete part 2.

Code Transformation
~~~~~~~~~~~~~~~~~~~

The approach I took was to make a 1:1 port from assembly to C:

[source,c]
----
include::iteration1.c[]
----

The next step is to add more structure to the program (removing ++goto++s and
labels):

[source,c]
----
include::iteration2.c[]
----

Shortening and combining some of the arithmetic expressions increases readability
dramatically, and every expression involving `g` can be incorporated into one of
the conditional jump expressions:

[source,c]
----
include::iteration3.c[]
----

The main body of both `do-while` loops is executed for all values of `d` and `e`
in the sequence (`2`, `3`, `4`, ..., `b-1`). This can be expressed more concisely
with two functionally equivalent `for` loops, and a similar transformation can be
performed on the outermost `while` loop:

[source,c]
----
include::iteration4.c[]
----

Code Optimization
~~~~~~~~~~~~~~~~~

At this point it appears that `h` is incremented each time a `b` in the sequence
(+106500 + **0***17+, +106500 + **1***17+, +106500 + **2***17+, ..., +106500
+ **1000***17+) has a divisor in the sequence (`2`, `3`, `4`, ..., `b-1`). In other
words, the program counts the numbers in the first sequence that are not prime
numbers.

A more efficient way to achieve the same result is to remove the inner loop and
use the modulo operator to identify divisors. I haven't benchmarked it (for
practical reasons), but this should result in at least a 200000x speedup compared
to the original code:

[source,c]
----
include::iteration5.c[]
----

The above C program provides the answer to the second part of the puzzle in less
than 50ms.

The equivalent optimized assembly (using `mod`) ends up looking like this:

[source,assembly]
----
include::optimized.asm[]
----
