Day 3: Perfectly Spherical Houses in a Vacuum
=============================================

https://adventofcode.com/2015/day/3

== Part 1

The first part of the puzzle asks you to find the number of grid locations
visited when following the move instructions in the puzzle input (including the
starting location). The locations counted must be unique: For instance, if the
input is +>>^+ (right, right, up), a total of +4+ locations are visited:
+(0,0)+, +(1,0)+, +(2,0)+, +(2,1)+. But if the input is +><<+ (right, left,
left), only +3+ distinct locations are visited: +(0,0)+, +(1,0)+, +(-1,0)+.

My solution consists of a simple shell pipeline and a few lines of AWK:

[source,shell]
----
grep -o . | awk -f coords.awk | sort | uniq | wc -l
----

The first command (+grep -o+) feeds one character per line to +awk+, which in
turn executes the script link:coords.awk[coords.awk], shown below:

[source,awk]
----
BEGIN { ew = ns = 0; print ew " " ns }
 /\^/ { ns++ }
  />/ { ew++ }
  /v/ { ns-- }
  /</ { ew-- }
      { print ew " " ns }
----

The variables +ew+ (_east-west_) and +ns+ (_north-south_) correspond to the
two axes of movement. For each line of input, one of these variables is either
incremented or decremented  depending on the directional character match
(+^+, +>+, +v+ or +<+), and the value of both variables are printed to +stdout+:

[source,shell]
----
$ echo ">><^" | grep -o . | awk -f coords.awk
----

Output:

----
0 0
1 0
2 0
1 0
1 1
----

Now the problem of identifying all locations visited at least once can be
reduced to removing duplicate lines (using +sort+/+uniq+):

[source,shell]
----
$ echo ">><^" | grep -o . | awk -f coords.awk | sort | uniq
----

Output:

----
0 0
1 0
1 1
2 0
----

+uniq+ only removes _adjacent_ duplicate lines, which is why +sort+ is needed.
The only remaining task is to count the lines, which is done trivially with
+wc+.

== Part 2

The second part of the puzzle asks the same question as part 1, except that
every second line of input should be interpreted as the movement instructions of
a _second actor_. If, for instance, the input is +>><^+, it is to be treated as
two seperate (but simultaneous) walks of the grid, namely +><+ and +>^+.

I solved it by creating an extended version of the solution from part 1, with
some minor differences, including:

* Capturing the newline-seperated input characters in a shell variable
  (+d="$(grep -o .)"+)

* Running a for loop twice, with the purpose of filtering movement instructions
  before passing them on to the coordinate creation script (+coords.awk+).

** Extracting even-numbered instructions during the first loop iteration
   (+sed -E 0~2d+).

** Extracting odd-numbered instructions during the second loop iteration
   (+sed -E 1~2d+).

* Combining the two seperate coordinate streams created in the loop by piping
  directly from the loop construction into the subsequent pipeline
  (+for ... do ... done | ...+).

The full solution is listed below:

[source,shell]
----
d="$(grep -o .)"
for i in 0 1
do echo "$d" | sed -E $i~2d | awk -f coords.awk
done | sort | uniq | wc -l
----
